### ISSUE TITLE
Is this repository being maintained?

### ISSUE THREAD

**Issue by guilhermeblanco** [terraform-providers/terraform-provider-postgresql#56]
No PRs being merged, no issues being responded, lots of bugs and limitations. And that's an official provider from Terraform...

**Comment by cliveza** [comment]
Yes, I want to know too, is this still being maintained?

**Comment by randomcamel** [comment]
Hi @guilhermeblanco!

I understand your frustration: it's not always clear from our repository structure who is responsible for different activity under `terraform-repositories`: HashiCorp manages the acceptance testing and release infrastructure, but we ourselves only steer development on a relative handful of them (most notably `aws`).

Earlier this year we went through the providers to make sure they all had maintainers, and this repo passed because we have a listed maintainer, Sean Chittenden (@sean-). Maybe he can chime in with his status, but in the meantime we're open to other maintainers joining.

There's another project in flight to programmatically audit repo activity, to catch cases like this, but I'd like to unblock this situation sooner. Hopefully Sean can add some context here; but if you have any suggestions for additional maintainers, please let me know here or at cdoherty@hashicorp.com.

Best,
Chris

**Comment by sean-** [comment]
I spend basically no time and effort on PostgreSQL-related items these days.  I'll cherry-pick issues periodically when I need a distraction from something else.  When I do need to spin something up for PostgreSQL, I do use the TF provider, but it's not that often anymore, and I almost never use RDS or any AWS services when using PostgreSQL.  If I can't test it or verify it, it's hard to do the work.  When this provider works for me, great!, but when it doesn't I roll up my sleeves and fix it.  It's open source, right?

This provider hasn't quite hit the hump of being a "killer way" to manage PostgreSQL schema yet so the attention it gets from the community writ large isn't huge.

I wish someone would invest more effort into this provider and get tables, sequences, and indexes working.  I don't know where I have a branch, but I have those three items there in some incomplete state (or more correctly, minimally viable, but wasn't quite done enough) and I ran out of time - and now lost track of - that work.

At some point I'm sure I'll become re-invested in this as most of my distributed persistence work revolves around CockroachDB.  Right now my needs are simple enough and because table/index support isn't available, we use a different schema migration technology that we embed directly in our installer binaries.  We're not wild about this either, but it's pragmatic given the tooling available.  If we could consume Terraform as a library and had this more fleshed out, we'd do that.  But until then?

**Comment by guilhermeblanco** [comment]
Hi all,

We use this driver extensively and had worked on its limitations, specially with RDS. Some forks are already way ahead in support as the official one, and I'd be more than happy to review the logic (I can't actually do Go) and merge if appropriate.

I'd say there're few critical pieces that would make working with PgSQL and TF much simpler in RDS. Implementing a grant support would already address the key limitation to be honest.

If anyone is interested, I'd be ok reviewing code, merging and releasing. =)

**Comment by cyrilgdn** [comment]
We are also using this provider (with RDS for production). We've done multiple developments in order to fix bugs and create missing resources (for our use case) like grant support, default privileges, etc.... Multiple PRs ( #51 #52 #53 #54 ) are open with our work. We still have some PRs to do (we have a quick "fix" for RDS that we need to work on).

I also sent an email to @randomcamel , I would be very interested to become a maintainers as I've already worked a lot on this provider and would be happy to integrate and enhance our work for the community.

For those who interested, our fork contains [a branch](https://github.com/edgelaboratories/terraform-provider-postgresql/tree/internal-release) that we are using with all our developments merged. (except the RDS fix that we need to rework and publish)

**Comment by cyrilgdn** [comment]
I'm now a new maintainer of this repo and I'll try to make it evolve. It may take a little while before the next release but it's my goal.

I close this issue for now but feel free it to comment if needed.

**Comment by sean-** [comment]
Congratulations @cyrilgdn!  I can't promise I'll be available, but if you have Q's, feel free to @ me to get my attention.
