### ISSUE TITLE
SQL injection safe queries

### ISSUE THREAD

**Issue by NinoFloris** [terraform-providers/terraform-provider-postgresql#96]
I expected each query here to be sql injection safe. Yes Terraform is usually used from a trusted context, but this doesn't mean each config variable is too. As it stands each query looks to be vulnerable.

example: https://github.com/terraform-providers/terraform-provider-postgresql/commit/7dccb185c75ff32cbabfea67b6adba4406b69976#diff-763c0b35a7889b804b094c50645c4860R212

**Comment by cyrilgdn** [comment]
Hi @NinoFloris,

Thank you for raising this issue!

Maybe I'm wrong so I probably need to think about it again but I think this query is safe as we use `pq.QuoteIdentifier` on values that are filled by the user (`owner`, `schema`, `role`) which avoids SQL injection.

`object_type` and `privileges` are not protected but they have validation functions which check that provided value(s) are part of a list defined in the code.  (For `privileges` it's not directly a `ValidateFunc` in the definition because the possible values depends on `object_type` so we are calling `validatePrivileges` by ourself in `resourcePostgreSQLDefaultPrivilegesCreate`)

**Comment by cyrilgdn** [comment]
@NinoFloris I close this issue but feel free to open it back and to comment if you disagree with my last comment.
